
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    # for live reload
  devtools:
    restart:
      additional-paths: src/main/webapp

  # config jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # update the scheme if necessary
      use-new-id-generator-mappings: false
    properties:
      format-sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

    # spring mail properties

