
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    # for live reload
  devtools:
    restart:
      additional-paths: src/main/webapp

  # config jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create # update the scheme if necessary
    properties:
      format-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  # security config
#  security:
#    user:
#      name: masum
#      password: masum
